### ISSUE TITLE
[Middleware_01] Complete GitHub Practice

### ISSUE THREAD

**Issue by juliawang2014** [andrewdimmer/csi-3370-software-project-config-test#37]
**What is the use case? Please describe.**
Practice using GitHub

**Tasks to Complete**

- [ ] Complete my GitHub Practice - @Bimmerboi-248 
- [ ] Complete my GitHub Practice - @martinhughes0722 
- [ ] Complete my GitHub Practice - @san4497 
- [ ] Complete my GitHub Practice - @shayat97 
- [ ] Complete my GitHub Practice - @Slackjaw1431 
- [ ] Complete my GitHub Practice - @BarczakS
- [ ] Complete my GitHub Practice - @yduong

**Additional context**
Refer to [here](https://github.com/andrewdimmer/csi-3370-software-project-config-test/tree/main/docs/practice) for instructions.
Programming pairs:
Pujan (Bimmerboi-248), Stan (BarczakS) and Talha (Slackjaw1431)
Martin (martinhughes0722) and Y (yduong)
Steven (san4497) and Syed (shayat97)

Contact Julia (juliawang2014) or Brenda (brendam19) for any needed assistance.
