### ISSUE TITLE
[Database] Complete GitHub Practice 

### ISSUE THREAD

**Issue by camrongrant1** [andrewdimmer/csi-3370-software-project-config-test#38]
**What is the use case? Please describe.**
A clear and concise description of what the use case is.

**Tasks to Complete**

- [ ] Complete my GitHub Practice - @Jake-wq 
- [ ] Complete my GitHub Practice - @MathewYaldo 
- [ ] Complete my GitHub Practice - @Endritz 
- [ ] Complete my GitHub Practice - @letthatbe 
- [ ] Complete my GitHub Practice - @Ian-Klaus
- [ ] Complete my GitHub Practice - @robertsonbrinker

**Additional context**
Refer [here](https://github.com/andrewdimmer/csi-3370-software-project-config-test/tree/main/docs/practice) for instructions.

Programming pairs:
Jake (Jake-wq) & Robertson (robertsonbrinker)
Mathew (MathewYaldo) & Kemal (letthatbe)
Ian (Ian-Klaus) & Endrit (Endritz)

Contact Cam'Ron (camrongrant1) and or Kyle (kylepoterek) of you need any assistance.
