### ISSUE TITLE
[Display_02] Complete GitHub Practice

### ISSUE THREAD

**Issue by jcortes18** [andrewdimmer/csi-3370-software-project-config-test#40]
**What is the use case? Please describe.**
Github Practice

**Tasks to Complete**

- [ ] Practice Using GitHub - @jcortes18
- [ ] Practice Using GitHub - @sydneyhill3901
- [ ] Practice Using GitHub - @Volter43
- [ ] Practice Using GitHub - @Dbaker19972
- [ ] Practice Using GitHub - @phardwoodward
- [ ] Practice Using GitHub - @Ahartman3
- [ ] Practice Using GitHub - @MetalMan1992
- [ ] Practice Using GitHub - @jmccloud827
- [ ] Practice Using GitHub - Yousif Sallan (need username)

**Additional context**
Instructions: [Here](https://github.com/andrewdimmer/csi-3370-software-project-config-test/tree/main/docs/practice)
Programming Pairs: 
1. Jessica - Sydney          
2. David - Yousif           
3. Paul - Anthony               
4. Tin - Jacob - Jonathan
