### ISSUE TITLE
[Display_01]

### ISSUE THREAD

**Issue by stevecatherman** [andrewdimmer/csi-3370-software-project-config-test#42]
**What is the use case? Please describe.**
Practice using Github

**Tasks to Complete**

- [ ] Complete my GitHub Practice - @EC01EC
- [ ] Complete my GitHub Practice - @stevecatherman
- [ ] Complete my GitHub Practice - @casher-ou
- [ ] Complete my GitHub Practice - @John-A11
- [ ] Complete my GitHub Practice - @elilley15
- [ ] Complete my GitHub Practice - @DLidz
- [ ] Complete my GitHub Practice - @atpoynter
- [ ] Complete my GitHub Practice - @reedsikorskiOU

**Additional context**
Refer to #36 here for instructions.
Programming pairs:
Steve (stevecatherman), and John (John-A11)
David (DLidz) and Reed (reedsikorskiOU)
Andrew (atpoynter) and Evan (elilley15)
Eric (EC01EC) and Cody (casher-ou)
