### ISSUE TITLE
[Middleware_02]

### ISSUE THREAD

**Issue by mckenzieking** [andrewdimmer/csi-3370-software-project-config-test#47]
**What is the use case? Please describe.**
Practice using GitHub

**Tasks to Complete**

- [ ] Complete GitHub Practice - @mckenzieking
- [ ] Complete GitHub Practice - @kwillard34
- [ ] Complete GitHub Practice - @tomtomtomcat
- [ ] Complete GitHub Practice - @nbergamin123
- [ ] Complete GitHub Practice - @rcapollari
- [ ] Complete GitHub Practice - @GitLee32
- [ ] Complete GitHub Practice - @Trode21
- [ ] Complete GitHub Practice - @NMoua-Edu
- [ ] Complete GitHub Practice - @windwakes

**Additional context**
Refer to [here](https://github.com/andrewdimmer/csi-3370-software-project-config-test/tree/main/docs/practice) for instructions.
Programming pairs:
1 Rayvin & Nikolaus
2 Rio & Ali
3 Tyler & Nou
4 Kal & Caleb

Contact Kenzie (Kenz#4119) or Kal (Kal Willard#4366) for any needed assistance.
